services:
  proxy-manager: # nginx
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - classlog-network

  backend:
    image: ${DOCKERHUB_USERNAME}/classlog-backend:${IMAGE_TAG}
    container_name: classlog-backend
    ports:
      - 8081:8081
    env_file:
      - backend/.env
    depends_on:
        redis:
          condition: service_healthy
        ai:
          condition: service_started
    volumes:
      - ./backend/src/main/resources/claog-1e23b-firebase-adminsdk-fbsvc-25a8b72901.json:/app/src/main/resources/claog-1e23b-firebase-adminsdk-fbsvc-25a8b72901.json:ro
    networks:
      - classlog-network
    restart: unless-stopped

  redis:
    image: redis
    container_name: classlog-redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10
    networks:
      - classlog-network
    restart: unless-stopped


  ai:
    image: classlog/ai:v4.1
    container_name: classlog-ai
    ports:
      - 8000:8000
    networks:
      - classlog-network
    env_file:
      - backend/.env
    restart: unless-stopped

  frontend:
    image: ${DOCKERHUB_USERNAME}/classlog-frontend:${IMAGE_TAG}
    container_name: classlog-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - frontend/.env
    networks:
      - classlog-network
    restart: unless-stopped

networks:
  classlog-network:
    driver: bridge