services:
#  springboot:
#    build: .
#    container_name: classlog-backend
#    ports:
#      - 8080:8080
#    env_file:
#      - .env
#    depends_on:
#      mysql:
#        condition: service_healthy
#      redis:
#        condition: service_healthy


#  mysql:
#    image: mysql
#    container_name: classlog-mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_DATABASE: ${DB_NAME}
#    volumes:
#      - ./mysql_data:/var/lib/mysql
#    ports:
#      - 3306:3306
#    healthcheck:
#      test: [ "CMD", "mysqladmin", "ping" ]
#      interval: 5s
#      retries: 10

  redis:
    image: redis
    container_name: classlog-redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10