services:
  springboot:
    build: .
    container_name: classlog-backend
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
#        mysql:
#          condition: service_healthy
#        redis:
#          condition: service_healthy
        ai:
          condition: service_started
    networks:
      - classlog-network

#  mysql:
#    image: mysql
#    container_name: classlog-mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_DATABASE: ${DB_NAME}
#    volumes:
#      - ./mysql_data:/var/lib/mysql
#    ports:
#      - 3306:3306
#    healthcheck:
#      test: [ "CMD", "mysqladmin", "ping" ]
#      interval: 5s
#      retries: 10
#
#  redis:
#    image: redis
#    container_name: classlog-redis
#    ports:
#      - 6379:6379
#    healthcheck:
#      test: [ "CMD", "redis-cli", "ping" ]
#      interval: 5s
#      retries: 10

  ai:
    image: classlog/ai:v1.1
    container_name: classlog-ai
    ports:
      - 8000:8000
    networks:
      - classlog-network
    env_file:
      - .env

networks:
  classlog-network:
    driver: bridge