name: ClassLog CI - Backend
on:
  pull_request:
    paths:
      - 'backend/**'
    branches: ["dev"]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name : Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name :  Set up redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: 7

      - name: Grant execute permission for gradlew
        working-directory: ./backend
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: ./backend
        env:
          DB_USERNAME: ${{ secrets.DB_HOST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AI_SERVER_URL: ${{ secrets.AI_SERVER_URL }}
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          KAKAO_API_KEY: ${{ secrets.KAKAO_API_KEY }}
          KAKAO_REDIRECT_URI: ${{ secrets.KAKAO_REDIRECT_URI }}
        run: ./gradlew build

      - name: ✅Passed
        if: success()
        run: echo "Backend Tests passed"

      - name: ❌Failed
        if: failure()
        run: echo "Backend Tests failed"